//////////////////////////////////////////////////////////////////////////
// Criacao...........: 02/2001
// Sistema...........: Olimpo - Automacao Comercial
// Analistas.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Desenvolvedores...: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Copyright.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
//////////////////////////////////////////////////////////////////////////

program Olimpo;

uses
  Forms,
  UnitPrincipal in 'UnitPrincipal.pas' {FrmPrincipal},
  unitDmDados in 'UnitDmdados.pas' {dmdados: TDataModule},
  UnitFechCaixa in 'UnitFechCaixa.pas' {FrmFechCaixa},
  UnitSobre in 'UnitSobre.pas' {FrmSobre},
  UniCadICMS in '..\Eros\UniCadICMS.pas' {FrmCadICMS},
  UnitAtSalario in '..\Eros\UnitAtSalario.pas' {FrmAtualSalario},
  UnitCadCliente in '..\Eros\UnitCadCliente.pas' {FrmCadCliente},
  UnitCadDepFunc in '..\Eros\UnitCadDepFunc.pas' {FrmCadDepFunc},
  UnitCadGrupo in '..\Eros\unitCadGrupo.pas' {FrmCadGrupo},
  UnitCadMarca in '..\Eros\unitCadMarca.pas' {FrmCadMarca},
  unitCadMaterial in '..\Eros\unitCadMaterial.pas' {FrmCadMaterial},
  UnitCadPlanos in '..\Eros\UnitCadPlanos.pas' {FrmCadPlanos},
  UnitCadSenha in '..\Eros\UnitCadSenha.pas' {frmCadSenha},
  UnitCadSubgrupo in '..\Eros\unitCadSubgrupo.pas' {FrmCadSubgrupo},
  UnitCadUnidade in '..\Eros\unitCadUnidade.pas' {FrmCadUnidades},
  unitCancelVenda in '..\Eros\unitCancelVenda.pas' {frmCancelVenda},
  UnitCargos in '..\Eros\UnitCargos.pas' {FrmCargos},
  UnitCarne in '..\Eros\UnitCarne.pas' {QRCarne: TQuickRep},
  UnitConsPlano in '..\Eros\UnitConsPlano.pas' {FrmConsPlano},
  UnitCustoFunc in '..\Eros\UnitCustoFunc.pas' {FrmCustoFunc},
  UnitDescProd in '..\Eros\UnitDescProd.pas' {FrmDescProd},
  unitEmitirNF in '..\Eros\unitEmitirNF.pas' {frmEmitirNF},
  unitFunc in '..\Eros\unitFunc.pas' {FrmFuncionario},
  unitLibCredito in '..\Eros\unitLibCredito.pas' {FrmLibCred},
  unitLocCliente in '..\Eros\unitLocCliente.pas' {FrmLocCliente},
  UnitLocFunc in '..\Eros\UnitLocFunc.pas' {FrmLocFunc},
  UnitLocProd in '..\Eros\UnitLocProd.pas' {FrmLocProd},
  unitLocVenda in '..\Eros\UnitLocVenda.pas' {FrmLocVenda},
  UnitNF in '..\Eros\UnitNF.pas' {FrmNF},
  unitOrcamento in '..\Eros\unitOrcamento.pas' {FrmOrcamento},
  unitParametro in '..\Eros\unitParametro.pas' {FrmParametro},
  unitPreco in '..\Eros\unitPreco.pas' {FrmLocPreco},
  UnitProduto in '..\Eros\UnitProduto.pas' {FrmProduto},
  UnitQRCliente in '..\Eros\UnitQRCliente.pas' {QRCliente: TQuickRep},
  unitQrComissao in '..\Eros\unitQrComissao.pas' {QrComissao},
  unitQrFatura in '..\Eros\unitQrFatura.pas' {QrFatura},
  UnitQRFunc in '..\Eros\UnitQRFunc.pas' {QRFunc: TQuickRep},
  unitQRNF in '..\Eros\unitQRNF.pas' {qrNF: TQuickRep},
  unitQrOrcamento in '..\Eros\unitQrOrcamento.pas' {QrOrcamento},
  unitQrPedidos in '..\Eros\unitQrPedidos.pas' {QrPedidosCli},
  unitQrPedidosFunc in '..\Eros\unitQrPedidosFunc.pas' {QrPedidosFunc},
  unitQrProduto in '..\Eros\unitQrProduto.pas' {QrProduto},
  unitQRVendas in '..\Eros\unitQRVendas.pas' {QrVenda},
  unitQrVendasCli in '..\Eros\unitQrVendasCli.pas' {QrVendaCli},
  UnitRelCliente in '..\Eros\UnitRelCliente.pas' {FrmRelCliente},
  unitRelFatura in '..\Eros\unitRelFatura.pas' {frmRelFatura},
  UnitRelFunc in '..\Eros\UnitRelFunc.pas' {FrmRelFunc},
  unitRelPedidos in '..\Eros\unitRelPedidos.pas' {frmRelPedidos},
  UnitVendas in '..\Eros\UnitVendas.pas' {FrmVendas},
  untDepende in '..\Eros\untDepende.pas' {frmDependentes},
  untOrca in '..\Eros\untOrca.pas' {frmOrca},
  unitBaixaCheque in '..\Ceres\unitBaixaCheque.pas' {FrmBaixaCheque},
  unitCadBancos in '..\Ceres\unitCadBancos.pas' {FrmCadBancos},
  unitConsultaCPF in '..\Ceres\unitConsultaCPF.pas' {FrmConsultaCPF},
  unitLanCheque in '..\Ceres\UnitLanCheque.pas' {FrmLanCheque},
  unitLanChequeSF in '..\Ceres\unitLanChequeSF.pas' {frmLanChequeSF},
  unitRelCheAberto in '..\Ceres\unitRelCheAberto.pas' {frmRelCheAberto},
  unitRenCheque in '..\Ceres\unitRenCheque.pas' {FrmRengCheque},
  untQRelCheAberto in '..\Ceres\untQRelCheAberto.pas' {qrRelCheAberto: TQuickRep},
  untRelCheAbreCli in '..\Ceres\untRelCheAbreCli.pas' {frmRelCheAbreCli},
  untRelCheDev in '..\Ceres\untRelCheDev.pas' {frmRelCheDev},
  untRelCheDevCli in '..\Ceres\untRelCheDevCli.pas' {frmRelCheDevCli},
  UnitCadFornec in '..\Pegasus\UnitCadFornec.pas' {FrmCadFornec},
  Unitcompra1 in '..\Pegasus\Unitcompra1.pas' {FrmRelCompras},
  unitCompras in '..\Pegasus\unitCompras.pas' {frmCompras},
  UnitEntradaMat in '..\Pegasus\unitEntradaMat.pas' {FrmEntradaMat},
  UnitLocFornec in '..\Pegasus\UnitLocFornec.pas' {FrmLocFornec},
  unitPagaVenda in '..\Eros\unitPagaVenda.pas' {frmPagaVenda},
  unitPagaPedido in '..\Pegasus\unitPagaPedido.pas' {frmPagaPedido},
  unitQrCompra in '..\Pegasus\unitQrCompra.pas' {QrCompra},
  Unitqrcompra1 in '..\Pegasus\Unitqrcompra1.pas' {qrcompra1: TQuickRep},
  UnitQREstoque in '..\Pegasus\UnitQREstoque.pas' {QREstoque: TQuickRep},
  unitQrEtiqueta in '..\Pegasus\unitQrEtiqueta.pas' {QrEtiqueta},
  UnitQRFornec in '..\Pegasus\UnitQRFornec.pas' {QRFornec: TQuickRep},
  unitRelCompras in '..\Pegasus\unitRelCompras.pas' {FrmRelCompPer},
  UnitSaidaMat in '..\Pegasus\unitSaidaMat.pas' {FrmSaidaMat},
  UnitRelEstoque in '..\Pegasus\UnitRelEstoque.pas' {FrmRelEstoque},
  unitRelEtiqueta in '..\Pegasus\unitRelEtiqueta.pas' {frmRelEtiqueta},
  UnitRelFornec in '..\Pegasus\UnitRelFornec.pas' {FrmRelFornec},
  uitQrSaExtratos in '..\Artemis\uitQrSaExtratos.pas' {QrSaExtrato},
  unitBaixaCpagar in '..\Artemis\unitBaixaCpagar.pas' {FrmBaixaCpagar},
  unitBaixaCreceber in '..\Artemis\unitBaixaCreceber.pas' {FrmBaixaCReceber},
  UnitBaixaLoteCP in '..\Artemis\UnitBaixaLoteCP.pas' {FrmBaixaLoteCP},
  UnitBaixaLoteCR in '..\Artemis\unitBaixaLoteCR.pas' {FrmBaixaLoteCR},
  unitBalFin in '..\Artemis\unitBalFin.pas' {FrmBalFin},
  Unitbolbbv in '..\Artemis\Unitbolbbv.pas' {QRBOLETO},
  Unitbolreal in '..\Artemis\Unitbolreal.pas' {QRBoleto1},
  UnitCadCartao in '..\Artemis\UnitCadCartao.pas' {FrmCadCartao},
  unitCadCcusto in '..\Artemis\unitCadCcusto.pas' {FrmCCusto},
  unitCadTipoDoc in '..\Artemis\unitCadTipoDoc.pas' {FrmTipoDoc},
  UnitCancelCP in '..\Artemis\UnitCancelCP.pas' {FrmCancelCP},
  UnitCancelCR in '..\Artemis\UnitCancelCR.pas' {FrmCancelCR},
  unitCcorrente in '..\Artemis\UnitCCorrente.pas' {FrmCCorrente},
  unitCpagar in '..\Artemis\unitCpagar.pas' {frmCpagar},
  unitCreceber in '..\Artemis\UnitCReceber.pas' {FrmCReceber},
  UnitDefContas in '..\Artemis\UnitDefContas.pas' {FrmDescParc},
  UnitTipoPagto in '..\Artemis\UnitTipoPagto.pas' {FrmTipoPgto},
  UnitFechCC in '..\Artemis\UnitFechCC.pas' {FrmFechCC},
  UnitHistorico in '..\Artemis\UnitHistorico.pas' {FrmHistorico},
  unitLocCcusto in '..\Artemis\UnitLocCCusto.pas' {FrmLocCCusto},
  unitLocCpagar in '..\Artemis\unitLocCpagar.pas' {FrmLocCpagar},
  unitLocCreceber in '..\Artemis\UnitLocCReceber.pas' {FrmLocCReceber},
  unitLocHistorico in '..\Artemis\UnitLocHistorico.pas' {FrmLocHistorico},
  unitLocTipoDoc in '..\Artemis\UnitLocTipoDoc.pas' {FrmLocTipoDoc},
  UnitMovCaixa in '..\Artemis\UnitMovCaixa.pas' {FrmMovCaixa},
  unitQRBalFin in '..\Artemis\unitQRBalFin.pas' {qrBalFin: TQuickRep},
  unitQrCpagar in '..\Artemis\unitQrCpagar.pas' {QrCpagar},
  UnitQRCReceber in '..\Artemis\UnitQRCReceber.pas' {QRCreceber: TQuickRep},
  unitQrImposto in '..\Artemis\unitQrImposto.pas' {QrImposto},
  UnitRelBoletoBBTXT in '..\Artemis\UnitRelBoletoBBTXT.pas' {FrmRelBoletoBBTXT},
  UnitRelBoletoBBV in '..\Artemis\UnitRelBoletoBBV.pas' {FrmRelBoletoBBV},
  UnitRelBoletoReal in '..\Artemis\UnitRelBoletoReal.pas' {FrmRelBoletoReal},
  UnitRelBoletoTXT in '..\Artemis\UnitRelBoletoTXT.pas' {FrmrelboletoTXT},
  unitRelCpagar in '..\Artemis\unitRelCpagar.pas' {frmRelCpagar},
  UnitRelCReceber in '..\Artemis\UnitRelCReceber.pas' {FrmRelCReceber},
  unitRelMovConta in '..\Artemis\unitRelMovConta.pas' {frmRelMovConta},
  unitRestauraCpagar in '..\Artemis\unitRestauraCpagar.pas' {FrmRestCP},
  unitRestauraCreceber in '..\Artemis\unitRestauraCreceber.pas' {FrmRestCR},
  UnitSelecCP in '..\Artemis\UnitSelecCP.pas' {FrmSelecCP},
  UnitTipoReceb in '..\Artemis\UnitTipoReceb.pas' {FrmTipoReceb},
  unitConfPagto in '..\Artemis\unitConfPagto.pas' {FrmConfPagto},
  unitConfReceb in '..\Artemis\unitConfReceb.pas' {FrmConfReceb},
  unitSelecCR in '..\Artemis\unitSelecCR.pas' {FrmSelecCR};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Olimpo 1.0';
  Application.CreateForm(Tdmdados, dmdados);
  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Run;
end.
